// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import Foundation
import NanoPack

let InvokeCallback_typeID: TypeID = 2

class InvokeCallback: NanoPackMessage {
  var typeID: TypeID { return 2 }

  let handle: Int32

  init(handle: Int32) {
    self.handle = handle
  }

  required init?(data: Data) {
    var ptr = data.startIndex + 8

    let handle: Int32 = data.read(at: ptr)
    ptr += 4

    self.handle = handle
  }

  required init?(data: Data, bytesRead: inout Int) {
    var ptr = data.startIndex + 8

    let handle: Int32 = data.read(at: ptr)
    ptr += 4

    self.handle = handle

    bytesRead = ptr - data.startIndex
  }

  func data() -> Data? {
    var data = Data()
    data.reserveCapacity(8)

    withUnsafeBytes(of: Int32(InvokeCallback_typeID)) {
      data.append(contentsOf: $0)
    }

    data.append([0], count: 1 * 4)

    data.write(size: 4, ofField: 1)
    data.append(int: handle)

    return data
  }
}
