// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import Foundation
import NanoPack

func makeNanoPackMessage(from data: Data) -> NanoPackMessage? {
    let typeID = data.readTypeID()
    switch typeID {
    case 320412644: return Button(data: data)
    case 370365707: return ReplyFromCallback(data: data)
    case 624966581: return UpdateWidgets(data: data)
    case 837166865: return ClickEvent(data: data)
    case 841129444: return TextField(data: data)
    case 1006836449: return Row(data: data)
    case 1016534798: return UpdateWidget(data: data)
    case 1100735111: return ListViewItem(data: data)
    case 1676374721: return Widget(data: data)
    case 1768749598: return OnValueChanged(data: data)
    case 1855640887: return Center(data: data)
    case 2013877267: return InvokeCallback(data: data)
    case 2164488861: return ListView(data: data)
    case 2313387354: return CreateWidget(data: data)
    case 2415007766: return Column(data: data)
    case 3495336243: return Text(data: data)
    case 3533765426: return CreateWindow(data: data)
    case 3591753548: return RenderItemConfig(data: data)
    default: return nil
    }
}
