// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import Foundation

enum Alignment: Int8 {
  case start = 0
  case end = 1
  case top = 2
  case bottom = 3
  case center = 4
  case spaceBetween = 5
  case spaceAround = 6
  case spaceEvenly = 7
}
