// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import Foundation
import NanoPack

let TextFieldChangedEvent_typeID: TypeID = 2_286_117_075

class TextFieldChangedEvent: NanoPackMessage {
  var typeID: TypeID { return 2_286_117_075 }

  var headerSize: Int { return 8 }

  let newValue: String

  init(newValue: String) {
    self.newValue = newValue
  }

  required init?(data: Data) {
    var ptr = data.startIndex + 8

    let newValueSize = data.readSize(ofField: 0)
    guard let newValue = data.read(at: ptr, withLength: newValueSize) else {
      return nil
    }
    ptr += newValueSize

    self.newValue = newValue
  }

  required init?(data: Data, bytesRead: inout Int) {
    var ptr = data.startIndex + 8

    let newValueSize = data.readSize(ofField: 0)
    guard let newValue = data.read(at: ptr, withLength: newValueSize) else {
      return nil
    }
    ptr += newValueSize

    self.newValue = newValue

    bytesRead = ptr - data.startIndex
  }

  func write(to data: inout Data, offset: Int) -> Int {
    let dataCountBefore = data.count

    data.reserveCapacity(offset + 8)

    data.append(typeID: TypeID(TextFieldChangedEvent_typeID))
    data.append([0], count: 1 * 4)

    data.write(size: newValue.lengthOfBytes(using: .utf8), ofField: 0, offset: offset)
    data.append(string: newValue)

    return data.count - dataCountBefore
  }

  func data() -> Data? {
    var data = Data()
    _ = write(to: &data, offset: 0)
    return data
  }
}
