// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import Foundation
import NanoPack

let TextField_typeID: TypeID = 841_129_444

class TextField: Widget {
  override var typeID: TypeID { return 841_129_444 }

  override var headerSize: Int { return 20 }

  let placeholder: String?
  let value: String
  let onValueChanged: UInt32

  init(tag: UInt32?, placeholder: String?, value: String, onValueChanged: UInt32) {
    self.placeholder = placeholder
    self.value = value
    self.onValueChanged = onValueChanged
    super.init(tag: tag)
  }

  required init?(data: Data) {
    var ptr = data.startIndex + 20

    var tag: UInt32?
    if data.readSize(ofField: 0) < 0 {
      tag = nil
    } else {
      tag = data.read(at: ptr)
      ptr += 4
    }

    var placeholder: String?
    if data.readSize(ofField: 1) < 0 {
      placeholder = nil
    } else {
      let placeholderSize = data.readSize(ofField: 1)
      guard let placeholder_ = data.read(at: ptr, withLength: placeholderSize) else {
        return nil
      }
      placeholder = placeholder_
      ptr += placeholderSize
    }

    let valueSize = data.readSize(ofField: 2)
    guard let value = data.read(at: ptr, withLength: valueSize) else {
      return nil
    }
    ptr += valueSize

    let onValueChanged: UInt32 = data.read(at: ptr)
    ptr += 4

    self.placeholder = placeholder
    self.value = value
    self.onValueChanged = onValueChanged
    super.init(tag: tag)
  }

  required init?(data: Data, bytesRead: inout Int) {
    var ptr = data.startIndex + 20

    var tag: UInt32?
    if data.readSize(ofField: 0) < 0 {
      tag = nil
    } else {
      tag = data.read(at: ptr)
      ptr += 4
    }

    var placeholder: String?
    if data.readSize(ofField: 1) < 0 {
      placeholder = nil
    } else {
      let placeholderSize = data.readSize(ofField: 1)
      guard let placeholder_ = data.read(at: ptr, withLength: placeholderSize) else {
        return nil
      }
      placeholder = placeholder_
      ptr += placeholderSize
    }

    let valueSize = data.readSize(ofField: 2)
    guard let value = data.read(at: ptr, withLength: valueSize) else {
      return nil
    }
    ptr += valueSize

    let onValueChanged: UInt32 = data.read(at: ptr)
    ptr += 4

    self.placeholder = placeholder
    self.value = value
    self.onValueChanged = onValueChanged
    super.init(tag: tag)

    bytesRead = ptr - data.startIndex
  }

  override func write(to data: inout Data, offset: Int) -> Int {
    let dataCountBefore = data.count

    data.reserveCapacity(offset + 20)

    data.append(typeID: TypeID(TextField_typeID))
    data.append([0], count: 4 * 4)

    if let tag = self.tag {
      data.write(size: 4, ofField: 0, offset: offset)
      data.append(int: tag)
    } else {
      data.write(size: -1, ofField: 0, offset: offset)
    }

    if let placeholder = self.placeholder {
      data.write(size: placeholder.lengthOfBytes(using: .utf8), ofField: 1, offset: offset)
      data.append(string: placeholder)
    } else {
      data.write(size: -1, ofField: 1, offset: offset)
    }

    data.write(size: value.lengthOfBytes(using: .utf8), ofField: 2, offset: offset)
    data.append(string: value)

    data.write(size: 4, ofField: 3, offset: offset)
    data.append(int: onValueChanged)

    return data.count - dataCountBefore
  }

  override func data() -> Data? {
    var data = Data()
    _ = write(to: &data, offset: 0)
    return data
  }
}
