// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import Foundation
import NanoPack

let ListViewItem_typeID: TypeID = 1_100_735_111

class ListViewItem: NanoPackMessage {
  var typeID: TypeID { return 1_100_735_111 }

  var headerSize: Int { return 12 }

  let itemTag: UInt32
  let widget: Widget

  init(itemTag: UInt32, widget: Widget) {
    self.itemTag = itemTag
    self.widget = widget
  }

  required init?(data: Data) {
    var ptr = data.startIndex + 12

    let itemTag: UInt32 = data.read(at: ptr)
    ptr += 4

    let widgetByteSize = data.readSize(ofField: 1)
    guard let widget = Widget.from(data: data[ptr...]) else {
      return nil
    }
    ptr += widgetByteSize

    self.itemTag = itemTag
    self.widget = widget
  }

  required init?(data: Data, bytesRead: inout Int) {
    var ptr = data.startIndex + 12

    let itemTag: UInt32 = data.read(at: ptr)
    ptr += 4

    let widgetByteSize = data.readSize(ofField: 1)
    guard let widget = Widget.from(data: data[ptr...]) else {
      return nil
    }
    ptr += widgetByteSize

    self.itemTag = itemTag
    self.widget = widget

    bytesRead = ptr - data.startIndex
  }

  func write(to data: inout Data, offset: Int) -> Int {
    let dataCountBefore = data.count

    data.reserveCapacity(offset + 12)

    data.append(typeID: TypeID(ListViewItem_typeID))
    data.append([0], count: 2 * 4)

    data.write(size: 4, ofField: 0, offset: offset)
    data.append(int: itemTag)

    let widgetByteSize = widget.write(to: &data, offset: data.count)
    data.write(size: widgetByteSize, ofField: 1, offset: offset)

    return data.count - dataCountBefore
  }

  func data() -> Data? {
    var data = Data()
    _ = write(to: &data, offset: 0)
    return data
  }
}
