// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import Foundation
import NanoPack

let ListViewBatchOperations_typeID: TypeID = 3_604_546_751

class ListViewBatchOperations: NanoPackMessage {
  var typeID: TypeID { return 3_604_546_751 }

  let operations: [ListViewOperation]

  init(operations: [ListViewOperation]) {
    self.operations = operations
  }

  required init?(data: Data) {
    var ptr = data.startIndex + 8

    let operationsItemCount = data.readSize(at: ptr)
    ptr += 4
    var operations: [ListViewOperation] = []
    operations.reserveCapacity(operationsItemCount)
    for _ in 0..<operationsItemCount {
      var iItemByteSize = 0
      guard let iItem = ListViewOperation.from(data: data[ptr...], bytesRead: &iItemByteSize) else {
        return nil
      }
      ptr += iItemByteSize
      operations.append(iItem)
    }

    self.operations = operations
  }

  required init?(data: Data, bytesRead: inout Int) {
    var ptr = data.startIndex + 8

    let operationsItemCount = data.readSize(at: ptr)
    ptr += 4
    var operations: [ListViewOperation] = []
    operations.reserveCapacity(operationsItemCount)
    for _ in 0..<operationsItemCount {
      var iItemByteSize = 0
      guard let iItem = ListViewOperation.from(data: data[ptr...], bytesRead: &iItemByteSize) else {
        return nil
      }
      ptr += iItemByteSize
      operations.append(iItem)
    }

    self.operations = operations

    bytesRead = ptr - data.startIndex
  }

  func data() -> Data? {
    let offset = 0

    var data = Data()
    data.reserveCapacity(8)

    data.append(typeID: TypeID(ListViewBatchOperations_typeID))
    data.append([0], count: 1 * 4)

    data.append(size: operations.count)
    var operationsByteSize: Size = 4
    for i in operations {
      guard let iData = i.data() else {
        return nil
      }
      data.append(iData)
      operationsByteSize += iData.count
    }
    data.write(size: operationsByteSize, ofField: 0, offset: offset)

    return data
  }

  func dataWithLengthPrefix() -> Data? {
    let offset = 4

    var data = Data()
    data.reserveCapacity(8 + 4)

    data.append(int: Int32(0))
    data.append(typeID: TypeID(ListViewBatchOperations_typeID))
    data.append([0], count: 1 * 4)

    data.append(size: operations.count)
    var operationsByteSize: Size = 4
    for i in operations {
      guard let iData = i.data() else {
        return nil
      }
      data.append(iData)
      operationsByteSize += iData.count
    }
    data.write(size: operationsByteSize, ofField: 0, offset: offset)

    data.write(size: data.count, at: 0)

    return data
  }
}
