// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import Foundation
import NanoPack

let ListViewInsertOperation_typeID: TypeID = 2_077_451_345

class ListViewInsertOperation: ListViewOperation {
  override var typeID: TypeID { return 2_077_451_345 }

  override var headerSize: Int { return 12 }

  let insertAt: [Int32]

  init(tag: Int32, insertAt: [Int32]) {
    self.insertAt = insertAt
    super.init(tag: tag)
  }

  required init?(data: Data) {
    var ptr = data.startIndex + 12

    let tag: Int32 = data.read(at: ptr)
    ptr += 4

    let insertAtByteSize = data.readSize(ofField: 1)
    let insertAtItemCount = insertAtByteSize / 4
    let insertAt = data[ptr..<ptr + insertAtByteSize].withUnsafeBytes {
      [Int32]($0.bindMemory(to: Int32.self).lazy.map { $0.littleEndian })
    }
    ptr += insertAtByteSize

    self.insertAt = insertAt
    super.init(tag: tag)
  }

  required init?(data: Data, bytesRead: inout Int) {
    var ptr = data.startIndex + 12

    let tag: Int32 = data.read(at: ptr)
    ptr += 4

    let insertAtByteSize = data.readSize(ofField: 1)
    let insertAtItemCount = insertAtByteSize / 4
    let insertAt = data[ptr..<ptr + insertAtByteSize].withUnsafeBytes {
      [Int32]($0.bindMemory(to: Int32.self).lazy.map { $0.littleEndian })
    }
    ptr += insertAtByteSize

    self.insertAt = insertAt
    super.init(tag: tag)

    bytesRead = ptr - data.startIndex
  }

  override func write(to data: inout Data, offset: Int) -> Int {
    let dataCountBefore = data.count

    data.reserveCapacity(offset + 12)

    data.append(typeID: TypeID(ListViewInsertOperation_typeID))
    data.append([0], count: 2 * 4)

    data.write(size: 4, ofField: 0, offset: offset)
    data.append(int: tag)

    data.write(size: insertAt.count * 4, ofField: 1, offset: offset)
    for i in insertAt {
      data.append(int: i)
    }

    return data.count - dataCountBefore
  }

  override func data() -> Data? {
    var data = Data()
    _ = write(to: &data, offset: 0)
    return data
  }
}
