// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import Foundation
import NanoPack

let RenderItemConfig_typeID: TypeID = 3_591_753_548

class RenderItemConfig: NanoPackMessage {
  var typeID: TypeID { return 3_591_753_548 }

  let sectionIndex: Int32
  let itemIndex: Int32

  init(sectionIndex: Int32, itemIndex: Int32) {
    self.sectionIndex = sectionIndex
    self.itemIndex = itemIndex
  }

  required init?(data: Data) {
    var ptr = data.startIndex + 12

    let sectionIndex: Int32 = data.read(at: ptr)
    ptr += 4

    let itemIndex: Int32 = data.read(at: ptr)
    ptr += 4

    self.sectionIndex = sectionIndex
    self.itemIndex = itemIndex
  }

  required init?(data: Data, bytesRead: inout Int) {
    var ptr = data.startIndex + 12

    let sectionIndex: Int32 = data.read(at: ptr)
    ptr += 4

    let itemIndex: Int32 = data.read(at: ptr)
    ptr += 4

    self.sectionIndex = sectionIndex
    self.itemIndex = itemIndex

    bytesRead = ptr - data.startIndex
  }

  func data() -> Data? {
    let offset = 0

    var data = Data()
    data.reserveCapacity(12)

    data.append(typeID: TypeID(RenderItemConfig_typeID))
    data.append([0], count: 2 * 4)

    data.write(size: 4, ofField: 0, offset: offset)
    data.append(int: sectionIndex)

    data.write(size: 4, ofField: 1, offset: offset)
    data.append(int: itemIndex)

    return data
  }

  func dataWithLengthPrefix() -> Data? {
    let offset = 4

    var data = Data()
    data.reserveCapacity(12 + 4)

    data.append(int: Int32(0))
    data.append(typeID: TypeID(RenderItemConfig_typeID))
    data.append([0], count: 2 * 4)

    data.write(size: 4, ofField: 0, offset: offset)
    data.append(int: sectionIndex)

    data.write(size: 4, ofField: 1, offset: offset)
    data.append(int: itemIndex)

    data.write(size: data.count, at: 0)

    return data
  }
}
