// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import Foundation
import NanoPack

let OnValueChanged_typeID: TypeID = 1051

class OnValueChanged: NanoPackMessage {
  var typeID: TypeID { return 1051 }

  let newValue: String

  init(newValue: String) {
    self.newValue = newValue
  }

  required init?(data: Data) {
    var ptr = data.startIndex + 8

    let newValueSize = data.readSize(ofField: 0)
    guard let newValue = data.read(at: ptr, withLength: newValueSize) else {
      return nil
    }
    ptr += newValueSize

    self.newValue = newValue
  }

  required init?(data: Data, bytesRead: inout Int) {
    var ptr = data.startIndex + 8

    let newValueSize = data.readSize(ofField: 0)
    guard let newValue = data.read(at: ptr, withLength: newValueSize) else {
      return nil
    }
    ptr += newValueSize

    self.newValue = newValue

    bytesRead = ptr - data.startIndex
  }

  func data() -> Data? {
    let offset = 0

    var data = Data()
    data.reserveCapacity(8)

    data.append(int: Int32(OnValueChanged_typeID))
    data.append([0], count: 1 * 4)

    data.write(size: newValue.lengthOfBytes(using: .utf8), ofField: 0, offset: offset)
    data.append(string: newValue)

    return data
  }

  func dataWithLengthPrefix() -> Data? {
    let offset = 4

    var data = Data()
    data.reserveCapacity(8 + 4)

    data.append(int: Int32(0))
    data.append(int: Int32(OnValueChanged_typeID))
    data.append([0], count: 1 * 4)

    data.write(size: newValue.lengthOfBytes(using: .utf8), ofField: 0, offset: offset)
    data.append(string: newValue)

    data.write(size: data.count, at: 0)

    return data
  }
}
