// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import Foundation
import NanoPack

let Column_typeID: TypeID = 103

class Column: Widget {
  override var typeID: TypeID { return 103 }

  let children: [Widget]

  init(tag: Int32?, children: [Widget]) {
    self.children = children
    super.init(tag: tag)
  }

  required init?(data: Data) {
    var ptr = data.startIndex + 12

    var tag: Int32?
    if data.readSize(ofField: 0) < 0 {
      tag = nil
    } else {
      tag = data.read(at: ptr)
      ptr += 4
    }

    let childrenItemCount = data.readSize(at: ptr)
    ptr += 4
    var children: [Widget] = []
    children.reserveCapacity(childrenItemCount)
    for _ in 0..<childrenItemCount {
      var iItemByteSize = 0
      guard let iItem = Widget(data: data[ptr...], bytesRead: &iItemByteSize) else {
        return nil
      }
      ptr += iItemByteSize
      children.append(iItem)
    }

    self.children = children
    super.init(tag: tag)
  }

  required init?(data: Data, bytesRead: inout Int) {
    var ptr = data.startIndex + 12

    var tag: Int32?
    if data.readSize(ofField: 0) < 0 {
      tag = nil
    } else {
      tag = data.read(at: ptr)
      ptr += 4
    }

    let childrenItemCount = data.readSize(at: ptr)
    ptr += 4
    var children: [Widget] = []
    children.reserveCapacity(childrenItemCount)
    for _ in 0..<childrenItemCount {
      var iItemByteSize = 0
      guard let iItem = Widget(data: data[ptr...], bytesRead: &iItemByteSize) else {
        return nil
      }
      ptr += iItemByteSize
      children.append(iItem)
    }

    self.children = children
    super.init(tag: tag)

    bytesRead = ptr - data.startIndex
  }

  override func data() -> Data? {
    var data = Data()
    data.reserveCapacity(12)

    withUnsafeBytes(of: Int32(Column_typeID)) {
      data.append(contentsOf: $0)
    }

    data.append([0], count: 2 * 4)

    if let tag = self.tag {
      data.write(size: 4, ofField: 0)
      data.append(int: tag)
    } else {
      data.write(size: -1, ofField: 0)
    }

    data.append(size: children.count)
    var childrenByteSize: Size = 4
    for i in children {
      guard let iData = i.data() else {
        return nil
      }
      data.append(iData)
      childrenByteSize += iData.count
    }
    data.write(size: childrenByteSize, ofField: 1)

    return data
  }
}
