// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import Foundation
import NanoPack

let Column_typeID: TypeID = 103

class Column: Widget {
  override var typeID: TypeID { return 103 }

  let children: [Widget]

  init(tag: Int32?, children: [Widget]) {
    self.children = children
    super.init(tag: tag)
  }

  required init?(data: Data) {
    var ptr = data.startIndex + 12

    let tag: Int32?
    if data.readSize(ofField: 0) < 0 {
      tag = nil
    } else {
      tag = data.read(at: ptr)
      ptr += 4
    }

    let childrenItemCount = data.readSize(at: ptr)
    ptr += 4
    var children: [Widget] = []
    children.reserveCapacity(childrenItemCount)
    for _ in 0..<childrenItemCount {
      var item0Size = 0
      guard let item0 = Widget.from(data: data[ptr...], bytesRead: &item0Size) else {
        return nil
      }
      ptr += item0Size
      children.append(item0)
    }

    self.children = children
    super.init(tag: tag)
  }

  required init?(data: Data, bytesRead: inout Int) {
    var ptr = data.startIndex + 12

    let tag: Int32?
    if data.readSize(ofField: 0) < 0 {
      tag = nil
    } else {
      tag = data.read(at: ptr)
      ptr += 4
    }

    let childrenItemCount = data.readSize(at: ptr)
    ptr += 4
    var children: [Widget] = []
    children.reserveCapacity(childrenItemCount)
    for _ in 0..<childrenItemCount {
      var item0Size = 0
      guard let item0 = Widget.from(data: data[ptr...], bytesRead: &item0Size) else {
        return nil
      }
      ptr += item0Size
      children.append(item0)
    }

    self.children = children
    super.init(tag: tag)

    bytesRead = ptr - data.startIndex
  }

  override func data() -> Data? {
    var data = Data()
    data.reserveCapacity(12)

    withUnsafeBytes(of: Int32(Column_typeID)) {
      data.append(contentsOf: $0)
    }

    data.append([0], count: 8)

    if let tag = self.tag {
      data.write(size: 4, ofField: 0)
      data.append(int: tag)
    } else {
      data.write(size: -1, ofField: 0)
    }

    var childrenTotalByteSize = 4
    data.append(size: children.count)
    for item0 in children {
      guard let item0Data = item0.data() else {
        return nil
      }
      data.append(item0Data)
      childrenTotalByteSize += item0Data.count
    }

    data.write(size: childrenTotalByteSize, ofField: 1)

    return data
  }
}
